[projects."/Users/jonasnatten/dev/ndla/backend"]
trust_level = "trusted"

[projects."/Users/jonasnatten/dev/ndla/deploy"]
trust_level = "trusted"

[projects."/Users/jonasnatten/dev/aero-workspace-cli"]
trust_level = "trusted"

[projects."/Users/jonasnatten/testing"]
trust_level = "trusted"

[projects."/Users/jonasnatten/logs"]
trust_level = "trusted"

[projects."/Users/jonasnatten/dev/dots"]
trust_level = "trusted"

[projects."/Users/jonasnatten/dev/ndla/ndla-frontend"]
trust_level = "trusted"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.idea]
command = "npx"
args = ["-y", "mcp-remote", "http://localhost:64342/sse"]

[mcp_servers.idea.env]
IJ_MCP_SERVER_PORT = "64342"
# IJ_MCP_SERVER_PROJECT_PATH = null

[mcp_servers.aws_documentation]
command = "uvx"
args = ["awslabs.aws-documentation-mcp-server@latest"]

[mcp_servers.aws_documentation.env]
FASTMCP_LOG_LEVEL = "ERROR"
AWS_DOCUMENTATION_PARTITION = "aws"

[mcp_servers.chrome_devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.aws-knowledge-mcp]
url = "https://knowledge-mcp.global.api.aws"

